### PR TITLE
[PE-D] Branch fix error message

### LINKED ISSUE #240: [PE-D][Tester D] link -c should require mandatory loc/ flag as specified in UG and help command
### Problem
The `link -c` command works even when the mandatory `loc/` flag is not provided. This is inconsistent with the User Guide (UG) and the help command output, both of which specify `loc/` as required.

Image

### Why this is a functionality bug
Allowing the command to work without a mandatory flag can confuse users and lead to unexpected behavior. It also reduces trust in the accuracy of the UG and help command documentation.

### Suggested improvement
Update the implementation of `link -c` so that the `loc/` flag is strictly required. The command should error if `loc/` is missing, aligning the actual behavior with documentation.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #250: [PE-D][Tester E] Incorrect example for link -e command
As stated in the title, the example is wrong but the command still works even with the extra parameter of n/

Image

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #253: [PE-D][Tester B] Appointment Location requirement ambiguity
When using the `link -c` command incorrectly, the following was shown by the app:

```
Invalid command format! 
Create flag: Links a new appointment to a client. 
Parameters: link -c n/NAME appt/DATE TIME len/MINUTES loc/LOCATION [type/TYPE] [msg/NOTES] [status/planned|confirmed|completed|cancelled]
Example: link -c n/Alex Wu appt/12-10-2025 1430 len/90 loc/Bukit Merah FSC type/home-visit msg/Bring consent form status/planned
```

In particular, the loc/LOCATION is not shown in brackets, but is an optional field, which could be confusing to users.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #259: [PE-D][Tester B] Typo in `link -e` invalid command format message
'''
Invalid command format! 
Edit flag: Updates an existing appointment for a client. 
Parameters: link -e id/ID [appt/DATE TIME] [len/MINUTES] [loc/LOCATION] [type/TYPE] [msg/NOTES] [status/planned|confirmed|completed|cancelled]
Example: link -e id/1234567 n/Alex Wu appt/12-10-2025 1430 len/90 loc/Bukit Merah FSC type/home-visit msg/Bring consent form status/planned
'''

When using the `link -e` command, the example shows a `n/Alex Wu` parameter in the command, which doesn't cause an error when executed but makes it confusing to the user.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #275: [PE-D][Tester C] JAR: s/o not allowed in name
`add n/James Ho s/o Tom p/92248444` is not allowed, even though `s/o` could be part of a legal name of a person
Image

Refer to course website:

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #280: [PE-D][Tester C] JAR: Unfriendly Edit Error Message
Entering `edit` gives:
Image

Whereas other commands like `link -c` would just use concise command template. (i.e. combinations of [] and ...notation)
Image

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by oilyfishball**
Regex do not allow empty name for Name.

Fixes #280
Fixes #275
Fixes #259
Fixes #253
Fixes #250
Fixes #240

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -10,13 +10,14 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names cannot contain any prefixes, and it should not be blank";
+
```
Comment (forestmu) [inline src/main/java/seedu/address/model/person/Name.java]: 10 LoC 👀 maybe can delete this extra blank line?
