### PR TITLE
Fix 30 Feb bug

### LINKED ISSUE #144: Throws invocation error when validating dates
For dates: 30 Feb

### PR DESCRIPTION
**Pull request by oilyfishball**
Fixes #144

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -69,7 +69,7 @@ public class EditCommand extends Command {
     private final EditPersonDescriptor editPersonDescriptor;
 
     /**
-     * @param indexName of the person in the filtered person list to edit
+     * @param indexName of the person in the unfiltered person list to edit
```
Comment (wongyuzhen) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Great attention to detail for changing the comment accordingly 🔥

File: src/main/java/seedu/address/model/appointment/AppointmentDateTime.java [hunk 2]
```diff
@@ -6,6 +6,7 @@
 import java.time.LocalDateTime;
 import java.time.format.DateTimeFormatter;
 import java.time.format.DateTimeParseException;
+import java.time.format.ResolverStyle;
```
Comment (wongyuzhen) [inline src/main/java/seedu/address/model/appointment/AppointmentDateTime.java]: Brilliant and elegant fix!

**Review by wongyuzhen — APPROVED** [review]
LGTM

File: src/main/java/seedu/address/model/appointment/AppointmentDateTime.java (hunk 2 above)
Comment (oilyfishball) [reply src/main/java/seedu/address/model/appointment/AppointmentDateTime.java]: Thank You!
